name: minimal-panel
channels:
- conda-forge
- defaults
dependencies:
- python=3.7
- biopython=1.74
- bokeh=1.2.0
- dask=2.1.0
- holoviews=1.12.3
- hvplot
- ipython
- jupyter
- jupyterlab
- pandas=0.24.0
- panel=0.6.0
- pyjanitor=0.18.0
- scikit-learn=0.21.2
